[package]
edition = "2021"
name = "przyczajony-tygrys"
version = "0.0.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
serial_test = "0.5.1"
